import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { API_ERROR_CODES, API_ERROR_MESSAGES_PL, API_ERROR_STATUS, LIMITS, WARNING_CODES } from "@pdf-insight/shared";

import { OPENAPI_CONFIG, createApp } from "../src/app";
import { memoryLimiter } from "../src/lib/rate-limit";

type Json = string | number | boolean | null | readonly Json[] | { readonly [key: string]: Json };
type JsonObject = Readonly<Record<string, Json>>;

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "../../..");
const OUT_JSON = join(ROOT, "docs/api/openapi.json");
const OUT_MD = join(ROOT, "docs/api/API.md");

function isObject(value: Json | undefined): value is JsonObject {
  return (
    value !== null && value !== undefined && !isJsonArray(value) && Object.getPrototypeOf(value) === Object.prototype
  );
}

function isJsonArray(value: Json | undefined): value is readonly Json[] {
  return Array.isArray(value);
}

function str(value: Json | undefined): string {
  if (value === undefined || value === null) return "";
  if (isJsonArray(value) || isObject(value)) return JSON.stringify(value);
  return String(value);
}

function refName(ref: string): string {
  return ref.replace("#/components/schemas/", "");
}

function typeOf(schema: JsonObject): string {
  const ref = schema.$ref;
  if (ref !== undefined) return `[${refName(str(ref))}](#${refName(str(ref)).toLowerCase()})`;
  const anyOf = schema.anyOf;
  if (isJsonArray(anyOf)) return anyOf.filter(isObject).map(typeOf).join(" \\| ");
  const type = schema.type;
  const base = isJsonArray(type) ? type.map(str).join(" \\| ") : str(type);
  if (base === "array" && isObject(schema.items)) return `${typeOf(schema.items)}[]`;
  const enumValues = schema.enum;
  if (isJsonArray(enumValues)) return enumValues.map((v) => `\`${str(v)}\``).join(" \\| ");
  if (schema.const !== undefined) return `\`${str(schema.const)}\``;
  return schema.format === undefined ? base || "any" : `${base} (${str(schema.format)})`;
}

function constraints(schema: JsonObject): string {
  const parts: string[] = [];
  const pairs: [string, string][] = [
    ["minLength", "min length"],
    ["maxLength", "max length"],
    ["minimum", "≥"],
    ["maximum", "≤"],
    ["minItems", "min items"],
    ["maxItems", "max items"],
    ["pattern", "pattern"],
  ];
  for (const [key, label] of pairs) {
    const value = schema[key];
    if (value !== undefined && !(key === "maximum" && Number(value) >= Number.MAX_SAFE_INTEGER)) {
      parts.push(key === "pattern" ? `${label} \`${str(value)}\`` : `${label} ${str(value)}`);
    }
  }
  const items = schema.items;
  if (isObject(items) && items.$ref === undefined) {
    const inner = constraints(items);
    if (inner.length > 0) parts.push(`items: ${inner}`);
  }
  return parts.join(", ");
}

function propertyTable(schema: JsonObject, prefix = ""): string[] {
  const properties = schema.properties;
  if (!isObject(properties)) return [];
  const required = new Set(isJsonArray(schema.required) ? schema.required.map(str) : []);
  const rows: string[] = [];
  for (const [name, raw] of Object.entries(properties)) {
    if (!isObject(raw)) continue;
    const field = `${prefix}${name}`;
    rows.push(
      `| \`${field}\` | ${typeOf(raw)} | ${required.has(name) ? "yes" : "no"} | ${constraints(raw)} | ${str(raw.description).replace(/\|/g, "\\|")} |`,
    );
    if (raw.type === "object") rows.push(...propertyTable(raw, `${field}.`));
  }
  return rows;
}

function renderMarkdown(doc: JsonObject): string {
  const info = isObject(doc.info) ? doc.info : {};
  const lines: string[] = [
    `# ${str(info.title)} — v${str(info.version)}`,
    "",
    "> Generated by `npm run docs:api` from the Zod schemas and Hono routes (ADR-0006). Do not edit.",
    "> `npm run docs:api:check` fails CI when this file no longer matches the code.",
    "",
    str(info.description),
    "",
    "## Endpoints",
    "",
  ];

  const paths = isObject(doc.paths) ? doc.paths : {};
  for (const [path, item] of Object.entries(paths)) {
    if (!isObject(item)) continue;
    for (const [method, op] of Object.entries(item)) {
      if (!isObject(op)) continue;
      lines.push(`### \`${method.toUpperCase()} ${path}\` — ${str(op.summary)}`, "");
      if (op.description !== undefined) lines.push(str(op.description), "");
      const parameters = isJsonArray(op.parameters) ? op.parameters : [];
      if (parameters.length > 0) {
        lines.push("| Parameter | In | Required | Type | Description |", "|---|---|---|---|---|");
        for (const parameter of parameters) {
          if (!isObject(parameter)) continue;
          const schema = isObject(parameter.schema) ? parameter.schema : {};
          lines.push(
            `| \`${str(parameter.name)}\` | ${str(parameter.in)} | ${parameter.required === true ? "yes" : "no"} | ${typeOf(schema)} | ${str(parameter.description ?? schema.description)} |`,
          );
        }
        lines.push("");
      }
      const body = isObject(op.requestBody) ? op.requestBody : null;
      const bodySchema =
        body !== null && isObject(body.content) && isObject(body.content["application/json"])
          ? body.content["application/json"].schema
          : undefined;
      if (isObject(bodySchema)) lines.push(`**Request body** (\`application/json\`): ${typeOf(bodySchema)}`, "");
      lines.push("| Status | Description | Body |", "|---|---|---|");
      const responses = isObject(op.responses) ? op.responses : {};
      for (const [status, response] of Object.entries(responses)) {
        if (!isObject(response)) continue;
        const content = isObject(response.content) ? response.content["application/json"] : undefined;
        const schema = isObject(content) ? content.schema : undefined;
        lines.push(`| ${status} | ${str(response.description)} | ${isObject(schema) ? typeOf(schema) : "—"} |`);
      }
      lines.push("");
    }
  }

  lines.push("## Error codes", "", "| Code | HTTP | Message (pl) |", "|---|---|---|");
  for (const code of API_ERROR_CODES)
    lines.push(`| \`${code}\` | ${API_ERROR_STATUS[code]} | ${API_ERROR_MESSAGES_PL[code]} |`);
  lines.push("", "## Warning codes", "", WARNING_CODES.map((code) => `\`${code}\``).join(" · "), "");

  lines.push("## Limits", "", "| Limit | Value |", "|---|---|");
  for (const [key, value] of Object.entries(LIMITS)) lines.push(`| \`${key}\` | ${value} |`);
  lines.push("", "## Schemas", "");

  const components = isObject(doc.components) && isObject(doc.components.schemas) ? doc.components.schemas : {};
  for (const [name, schema] of Object.entries(components)) {
    if (!isObject(schema)) continue;
    lines.push(`### ${name}`, "");
    if (schema.description !== undefined) lines.push(str(schema.description), "");
    lines.push(
      "| Field | Type | Required | Constraints | Description |",
      "|---|---|---|---|---|",
      ...propertyTable(schema),
      "",
    );
  }
  return `${lines
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .trimEnd()}\n`;
}

const app = createApp({
  fetch: () => Promise.resolve(new Response(null, { status: 500 })),
  now: () => 0,
  uuid: () => "00000000-0000-4000-8000-000000000000",
  logger: { log: () => undefined },
  fallbackLimiter: memoryLimiter(1, 1, () => 0),
});
// SAFETY: parsing the output of JSON.stringify yields JSON by construction.
const docJson = JSON.parse(JSON.stringify(app.getOpenAPI31Document(OPENAPI_CONFIG))) as Json;
if (!isObject(docJson)) throw new Error("OpenAPI document must be an object");

const outputs: [string, string][] = [
  [OUT_JSON, `${JSON.stringify(docJson, null, 2)}\n`],
  [OUT_MD, renderMarkdown(docJson)],
];

const mode = process.argv.includes("--check") ? "check" : "write";
if (mode === "write") {
  for (const [path, content] of outputs) writeFileSync(path, content);
  process.stdout.write(`Wrote ${outputs.map(([p]) => p.replace(`${ROOT}/`, "")).join(", ")}\n`);
} else {
  const stale = outputs.filter(([path, content]) => {
    try {
      return readFileSync(path, "utf8") !== content;
    } catch {
      return true;
    }
  });
  if (stale.length > 0) {
    process.stderr.write(
      `API docs drifted from the code: ${stale.map(([p]) => p.replace(`${ROOT}/`, "")).join(", ")}\n` +
        "The committed docs are the intended contract. If the change is intended, run `npm run docs:api` and review the diff; otherwise fix the code.\n",
    );
    process.exit(1);
  }
  process.stdout.write("API docs match the code.\n");
}
